### ISSUE TITLE
Using a cPanel API token instead of a cPanel account password

### ISSUE THREAD

**Issue by BenPi-Ross** [kdeenkhoorn/dns_cpaneldns#5]
Hello!

It's not really an issue, but more a proof of concept for a future update of the script.

Since the version of cPanel I use have the possibility to create a token to access the API, I tried to modify the code to use a token instead of the cPanel account user password.

All I did is modify the lines 223 and 224 as follow :
`  basicauth="$(printf %s "$CPANELDNS_AUTH_ID:$CPANELDNS_AUTH_PASSWORD")"`
`  export _H1="Authorization: cpanel $basicauth"`
The script now successfully use the token instead of the password to authenticate.

So to my untrained eye, it seems the script could be easily modified to accept both the password or a token (or only the token).

Have a nice day!

BenPi

**Comment by kdeenkhoorn** [comment]
Thanks for the input BenPi-Ross.

Unfortunately currently i have no CPanel instance availible to test this, can you tell if username/password still works after this modification ?
Because of the used Basic authentication method the string has to be base64 encoded.
If the cpanel authentication does not need this for both username/password and API key authentication this is a solution.
And how did you configure the API token, which variables did you use ?

Thanks in advance,

Kl@@s
